Add type casts to malloc and realloc in C-Sources (#3378)
So far some allocations do cast, some don't.
It is required if compiled with C++ to avoid errors like:

In file included from ./OMCppBuildings_latest_Buildings.BoundaryConditions.WeatherData.Examples.ReaderTMY3Functions.cpp:7:
Buildings 10.0.0-master/Resources/C-Sources/getTimeSpan.c:27:9: error: cannot initialize a variable of type 'char *' with an rvalue of type 'void *'
  char *result = malloc(len1 + len2 + 1);
        ^        ~~~~~~~~~~~~~~~~~~~~~~~

or

In file included from ./OMCppBuildings_latest_Buildings.Utilities.Plotters.Examples.ScatterFunctions.cpp:8:
Buildings 10.0.0-master/Resources/C-Sources/plotInit.c:42:21: error: assigning to 'char **' from incompatible type 'void *'
    plotFileNames = malloc(sizeof(char*));
                    ^~~~~~~~~~~~~~~~~~~~~