Changed python to python3
This is needed on my desktop.
Otherwise, I get make -f Buildings/Resources/Scripts/travis/Makefile test-optimica PACKAGE=Buildings.Utilities.IO.Python36
(cd /home/mwetter/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings/Buildings &&   export PYTHONPATH=/home/mwetter/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings/Buildings/Resources/Python-Sources &&   python ../bin/runUnitTests.py --batch --single-package Buildings.Utilities.IO.Python36 --tool optimica --skip-verification)
Traceback (most recent call last):
  File ../bin/runUnitTests.py, line 207, in <module>
    skip_verification=args.skip_verification
  File ../bin/runUnitTests.py, line 77, in _runUnitTests
    import buildingspy.development.regressiontest as u
  File /home/mwetter/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings/Buildings/../../BuildingsPy/buildingspy/development/regressiontest.py, line 42, in <module>
    import pyfunnel
ImportError: No module named pyfunnel
Buildings/Resources/Scripts/travis/Makefile:66: recipe for target 'test-optimica' failed
make: *** [test-optimica] Error 1